# Nome da nossa aplicação
spring.application.name=Cash-Flow

# 1. Configurações de conexão do Banco H2 (Banco em memória)
spring.datasource.url=jdbc:h2:mem:cashflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Habilitar a interface web do H2 (para podermos ver as tabelas no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Configurações do JPA / Hibernate (A "mágica" do banco)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# O 'update' diz para o Spring: "Leia minhas classes Java e crie as tabelas automaticamente se elas não existirem"
spring.jpa.hibernate.ddl-auto=update
# O 'true' faz o Spring imprimir no console do IntelliJ os comandos SQL que ele está rodando por trás dos panos
spring.jpa.show-sql=true